import type { NavItem } from '@/types/navigation'

export const navigationItems: NavItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: 'dashboard',
    route: '/',
    roles: ['admin', 'recruiter', 'manager', 'client'],
  },
  {
    id: 'employees',
    label: 'Employees',
    icon: 'employees',
    route: '/employees',
    roles: ['admin'],
  },
  {
    id: 'users',
    label: 'User Management',
    icon: 'users',
    route: '/users',
    roles: ['admin'],
  },
  {
    id: 'organizations',
    label: 'Organizations',
    icon: 'organizations',
    route: '/organizations',
    roles: ['admin'],
  },
  {
    id: 'recruitment',
    label: 'Recruitment',
    icon: 'recruitment',
    route: '/recruitment',
    roles: ['admin', 'recruiter', 'manager'],
  },
  {
    id: 'candidates',
    label: 'Candidates',
    icon: 'candidates',
    route: '/candidates',
    roles: ['recruiter', 'client'],
  },
  {
    id: 'pipeline',
    label: 'Pipeline',
    icon: 'pipeline',
    route: '/pipeline',
    roles: ['admin', 'recruiter'],
  },
  {
    id: 'interviews',
    label: 'Interviews',
    icon: 'interviews',
    route: '/interviews',
    roles: ['recruiter', 'client'],
  },
  {
    id: 'job-postings',
    label: 'Job Postings',
    icon: 'job-postings',
    route: '/job-postings',
    roles: ['client'],
  },
  {
    id: 'team',
    label: 'My Team',
    icon: 'team',
    route: '/team',
    roles: ['manager'],
  },
  {
    id: 'approvals',
    label: 'Approvals',
    icon: 'approvals',
    route: '/approvals',
    roles: ['manager'],
  },
  {
    id: 'reports',
    label: 'Reports',
    icon: 'reports',
    route: '/reports',
    roles: ['admin', 'manager'],
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: 'settings',
    route: '/settings',
    roles: ['admin', 'recruiter', 'manager', 'client'],
  },
]
